#!/bin/bash


function manageShare () {

	local FILE_SHARE_PATH="$1"
	local FILE_SHARE_NAME="$2"
	local FILE_SHARE_TYPE="$3"	# afp=100 smb=001 both=101 none=000
	local FILE_SHARE_OWNER="$4"
	
	#	verify file share path exist
	if ! [ -d "$FILE_SHARE_PATH" ]; then
		if ! /bin/mkdir -p "$FILE_SHARE_PATH"; then 
			echo "ERROR: Unable to create specified folder for [$FILE_SHARE_PATH]." >&2
			return $LINENO
		fi
	fi

	#	enable smb
	if ! /bin/launchctl list com.apple.smbd &> /dev/null && [ ${FILE_SHARE_TYPE:2:2} -eq 1 ]; then 
		if ! /bin/launchctl load -w /System/Library/LaunchDaemons/com.apple.smbd.plist; then
			echo "ERROR: Unable to load SMB sharing service."
			return $LINENO
		fi
	fi 

	#	enable afp
	if ! /bin/launchctl list com.apple.AppleFileServer &> /dev/null && [ ${FILE_SHARE_TYPE:0:0} -eq 1 ]; then 
		if ! /bin/launchctl load -w /System/Library/LaunchDaemons/com.apple.AppleFileServer.plist; then
			echo "ERROR: Unable to load AFP sharing service."
			return $LINENO
		fi
	fi

	#	enable file share
	if ! /usr/sbin/sharing -l | grep -c "$FILE_SHARE_PATH" &> /dev/null; then
		if ! /usr/sbin/sharing -a "$FILE_SHARE_PATH" -n "$FILE_SHARE_NAME" -s $FILE_SHARE_TYPE -g 000; then
			echo "ERROR: Unable to enable file share for [$FILE_SHARE_NAME]." >&2
			return $LINENO
		fi
	fi

	#	set file share ownership (optional)
	if [ -n $FILE_SHARE_OWNER ]; then 

		#	verify file share ownership format
		if ! echo $FILE_SHARE_OWNER | /usr/bin/grep ":" &> /dev/null; then
			echo "ERROR: Expected format not found [user:group]." >&2
			return $LINENO
		fi

		#	set ownership as spcified
		if ! /usr/sbin/chown -R "$FILE_SHARE_OWNER" "$FILE_SHARE_PATH" &> /dev/null; then
			echo  "ERROR: Unable to set permissions for [$FILE_SHARE_PATH]." >&2
			return $LINENO
		fi
	fi

	return 0
}


function main () {

	# $1 path to share	
	# $2 name of share  	
	# $3 type afp=100 smb=001 both=101 none=000
	# $4 ownership owner:group 	
	manageShare "/Users/test" "Bogus" "101" "macsuper:staff"
	
}


#	run main if called directly
if [[ "$BASH_SOURCE" == "$0" ]]; then
    main
fi
