#!/bin/bash 


function isAdAccessible () {

	local SEARCH_PATH=`/usr/bin/dscl /Search -read . CSPSearchPath | /usr/bin/grep "Active Directory" 2> /dev/null`

	if /usr/bin/dscl "$SEARCH_PATH" read . dsAttrTypeNative:DomainName &> /dev/null; then 
		return 0
	else 
		return 1
	fi

}


function main () {

	if isAdAccessible; then 
		echo "Yes"
	else
		echo "No"
	fi

}


#	run main if called directly
if [[ "$BASH_SOURCE" == "$0" ]]; then
    main
fi
